const images: { [key: string]: string } = {
  "BatchAI": "AI and ML Service Color/BatchAI.png",
  "BotServices": "AI and ML Service Color/BotServices.png",
  "CognitiveServices": "AI and ML Service Color/CognitiveServices.png",
  "GenomicsAccounts": "AI and ML Service Color/GenomicsAccounts.png",
  "MachineLearningServiceWorkspaces": "AI and ML Service Color/MachineLearningServiceWorkspaces.png",
  "MachineLearningStudioWebServicePlans": "AI and ML Service Color/MachineLearningStudioWebServicePlans.png",
  "MachineLearningStudioWebServices": "AI and ML Service Color/MachineLearningStudioWebServices.png",
  "MachineLearningStudioWorkspaces": "AI and ML Service Color/MachineLearningStudioWorkspaces.png",
  "AnalysisServices": "Analytics Service Color/AnalysisServices.png",
  "AzureDatabricks": "Analytics Service Color/AzureDatabricks.png",
  "AzureDataExplorerClusters": "Analytics Service Color/AzureDataExplorerClusters.png",
  "DataFactories": "Analytics Service Color/DataFactories.png",
  "DataLakeAnalytics": "Analytics Service Color/DataLakeAnalytics.png",
  "DataLakeStoreGen1": "Analytics Service Color/DataLakeStoreGen1.png",
  "EventHubClusters": "Analytics Service Color/EventHubClusters.png",
  "EventHubs": "Analytics Service Color/EventHubs.png",
  "HDInsightClusters": "Analytics Service Color/HDInsightClusters.png",
  "Workspaces": "Analytics Service Color/LogAnalyticsWorkspaces.png",
  "StreamAnalyticsJobs": "Analytics Service Color/StreamAnalyticsJobs.png",
  "BatchAccounts": "Compute Service Color/BatchAccounts.png",
  "CitrixVirtualDesktopsEssentials": "Compute Service Color/CitrixVirtualDesktopsEssentials.png",
  "CloudServices": "Compute Service Color/CloudServices.png",
  "CloudSimpleVirtualMachines": "Compute Service Color/CloudSimpleVirtualMachines.png",
  "Disks": "Compute Service Color/Disks.png",
  "DiskSnapshots": "Compute Service Color/DiskSnapshots.png",
  "FunctionApps": "Compute Service Color/FunctionApps.png",
  "MeshApplications": "Compute Service Color/MeshApplications.png",
  "SAPHANAonAzure": "Compute Service Color/SAPHANAonAzure.png",
  "ServiceFabricClusters": "Compute Service Color/ServiceFabricClusters.png",
  "VMImages": "Compute Service Color/VMImages.png",
  "AvailabilitySets": "Compute Service Color/VM/AvailabilitySets.png",
  "Non-azure-machine": "Compute Service Color/VM/Non-azure-machine.png",
  "OSImages": "Compute Service Color/VM/OSImages(Classic).png",
  "VM": "Compute Service Color/VM/VM(Classic).png",
  "VM-Linux-non-azure": "Compute Service Color/VM/VM-Linux-non-azure.png",
  "VM-Linux": "Compute Service Color/VM/VM-Linux.png",
  "VM-non-azure": "Compute Service Color/VM/VM-non-azure.png",
  "VM-windows-non-azure": "Compute Service Color/VM/VM-windows-non-azure.png",
  "VM-windows": "Compute Service Color/VM/VM-windows.png",
  "virtualMachines": "Compute Service Color/VM/VM.png",
  "VMScaleSets": "Compute Service Color/VM/VMScaleSets.png",
  "ContainerInstances": "Container Service Color/ContainerInstances.png",
  "ContainerRegistries": "Container Service Color/ContainerRegistries.png",
  "KubernetesServices": "Container Service Color/KubernetesServices.png",
  "AzureCacheforRedis": "Databases Service Color/AzureCacheforRedis.png",
  "AzureCacheplusRedis": "Databases Service Color/AzureCacheplusRedis.png",
  "AzureCosmosDB": "Databases Service Color/AzureCosmosDB.png",
  "AzureDatabase(Generic)": "Databases Service Color/AzureDatabase(Generic).png",
  "AzureDatabaseforMariaDBservers": "Databases Service Color/AzureDatabaseforMariaDBservers.png",
  "AzureDatabaseforMySQLservers": "Databases Service Color/AzureDatabaseforMySQLservers.png",
  "AzureDatabaseforPostgreSQLservers": "Databases Service Color/AzureDatabaseforPostgreSQLservers.png",
  "AzureSQLDataWarehouse": "Databases Service Color/AzureSQLDataWarehouse.png",
  "BlobStorage": "Databases Service Color/BlobStorage.png",
  "DataLake": "Databases Service Color/DataLake.png",
  "ElasticDatabasePools": "Databases Service Color/ElasticDatabasePools.png",
  "ElasticJobAgents": "Databases Service Color/ElasticJobAgents.png",
  "ManagedDatabases": "Databases Service Color/ManagedDatabases.png",
  "SQLDatabases": "Databases Service Color/SQLDatabases.png",
  "SQLManagedInstances": "Databases Service Color/SQLManagedInstances.png",
  "SQLServers": "Databases Service Color/SQLServers.png",
  "SQLServerstretchDatabases": "Databases Service Color/SQLServerstretchDatabases.png",
  "VirtualClusters": "Databases Service Color/VirtualClusters.png",
  "VirtualDatacenter": "Databases Service Color/VirtualDatacenter.png",
  "ApplicationInsights": "DevOps Service Color/ApplicationInsights.png",
  "AzureArtifacts": "DevOps Service Color/AzureArtifacts.png",
  "AzureBoards": "DevOps Service Color/AzureBoards.png",
  "AzureDevOps": "DevOps Service Color/AzureDevOps.png",
  "AzureDevTestLabs": "DevOps Service Color/AzureDevTestLabs.png",
  "AzurePipelines": "DevOps Service Color/AzurePipelines.png",
  "AzureRepos": "DevOps Service Color/AzureRepos.png",
  "AzureTestPlans": "DevOps Service Color/AzureTestPlans.png",
  "AllResources": "General Service Icons/AllResources.png",
  "AzureHome": "General Service Icons/AzureHome.png",
  "DeveloperTools": "General Service Icons/DeveloperTools.png",
  "Help+Support": "General Service Icons/Help+Support.png",
  "Information": "General Service Icons/Information.png",
  "ManagementGroups": "General Service Icons/ManagementGroups.png",
  "Marketplace": "General Service Icons/Marketplace.png",
  "QuickStartCenter": "General Service Icons/QuickStartCenter.png",
  "Recent": "General Service Icons/Recent.png",
  "Reservations": "General Service Icons/Reservations.png",
  "Resource": "General Service Icons/Resource.png",
  "ResourceGroups": "General Service Icons/ResourceGroups.png",
  "ServiceHealth": "General Service Icons/ServiceHealth.png",
  "SharedDashboard": "General Service Icons/SharedDashboard.png",
  "Subscriptions": "General Service Icons/Subscriptions.png",
  "Support": "General Service Icons/Support.png",
  "SupportRequests": "General Service Icons/SupportRequests.png",
  "Tag": "General Service Icons/Tag.png",
  "Tags": "General Service Icons/Tags.png",
  "Templates": "General Service Icons/Templates.png",
  "TwoUserIcon": "General Service Icons/TwoUserIcon.png",
  "UserHealthIcon": "General Service Icons/UserHealthIcon.png",
  "UserIcon": "General Service Icons/UserIcon.png",
  "UserPrivacy": "General Service Icons/UserPrivacy.png",
  "UserResource": "General Service Icons/UserResource.png",
  "What'sNew": "General Service Icons/What'sNew.png",
  "AccessReview": "Identity Service Color/AccessReview.png",
  "ActiveDirectory": "Identity Service Color/ActiveDirectory.png",
  "ActiveDirectoryConnectHealth": "Identity Service Color/ActiveDirectoryConnectHealth.png",
  "AppRegistrations": "Identity Service Color/AppRegistrations.png",
  "AzureADB2C": "Identity Service Color/AzureADB2C.png",
  "AzureADDomainServices": "Identity Service Color/AzureADDomainServices.png",
  "AzureADIdentityProtection": "Identity Service Color/AzureADIdentityProtection.png",
  "AzureADPrivilegedIdentityManagement": "Identity Service Color/AzureADPrivilegedIdentityManagement.png",
  "AzureInformationProtection": "Identity Service Color/AzureInformationProtection.png",
  "ConditionalAccess": "Identity Service Color/ConditionalAccess.png",
  "EnterpriseApplications": "Identity Service Color/EnterpriseApplications.png",
  "Identitygovernance": "Identity Service Color/Identitygovernance.png",
  "ManagedIdentities": "Identity Service Color/ManagedIdentities.png",
  "APIManagementServices": "Integration Service Color/APIManagementServices.png",
  "AppConfiguration": "Integration Service Color/AppConfiguration.png",
  "AzureAPIforFHIR": "Integration Service Color/AzureAPIforFHIR.png",
  "AzureDataCatalog": "Integration Service Color/AzureDataCatalog.png",
  "AzureServiceBus": "Integration Service Color/AzureServiceBus.png",
  "AzureServiceBusRelays": "Integration Service Color/AzureServiceBusRelays.png",
  "AzureStorSimpleDeviceManagers": "Integration Service Color/AzureStorSimpleDeviceManagers.png",
  "EventGridDomains": "Integration Service Color/EventGridDomains.png",
  "EventGridSubscriptions": "Integration Service Color/EventGridSubscriptions.png",
  "EventGridTopics": "Integration Service Color/EventGridTopics.png",
  "IntegrationAccounts": "Integration Service Color/IntegrationAccounts.png",
  "IntegrationServiceEnvironments": "Integration Service Color/IntegrationServiceEnvironments.png",
  "LogicApps": "Integration Service Color/LogicApps.png",
  "LogicAppsCustomConnector": "Integration Service Color/LogicAppsCustomConnector.png",
  "SendGridAccounts": "Integration Service Color/SendGridAccounts.png",
  "ServiceCatalogManagedApplicationDefinitions": "Integration Service Color/ServiceCatalogManagedApplicationDefinitions.png",
  "SoftwareasaService(SaaS)": "Integration Service Color/SoftwareasaService(SaaS).png",
  "AzureDigitalTwins": "Internet of Things Service Color/AzureDigitalTwins.png",
  "AzureIoTHub": "Internet of Things Service Color/AzureIoTHub.png",
  "AzureIoTHubSecurity": "Internet of Things Service Color/AzureIoTHubSecurity.png",
  "AzureMaps": "Internet of Things Service Color/AzureMaps.png",
  "AzureSphere": "Internet of Things Service Color/AzureSphere.png",
  "DeviceProvisioningServices": "Internet of Things Service Color/DeviceProvisioningServices.png",
  "IoTCentralApplications": "Internet of Things Service Color/IoTCentralApplications.png",
  "TimeSeriesInsightsenvironments": "Internet of Things Service Color/TimeSeriesInsightsenvironments.png",
  "TimeSeriesInsightsEventsSources": "Internet of Things Service Color/TimeSeriesInsightsEventsSources.png",
  "Windows10IoTCoreServices": "Internet of Things Service Color/Windows10IoTCoreServices.png",
  "ClientApps": "Intune Service Color/ClientApps.png",
  "DedicatedEventHub": "Intune Service Color/DedicatedEventHub.png",
  "DeviceCompliance": "Intune Service Color/DeviceCompliance.png",
  "DeviceConfig": "Intune Service Color/DeviceConfig.png",
  "DevicesGroups": "Intune Service Color/DevicesGroups.png",
  "eBooks": "Intune Service Color/eBooks.png",
  "Enrollment": "Intune Service Color/Enrollment.png",
  "ExchangeOn-PremisesAccess": "Intune Service Color/ExchangeOn-PremisesAccess.png",
  "IntuneAppProtection": "Intune Service Color/IntuneAppProtection.png",
  "ManagedDesktop": "Intune Service Color/ManagedDesktop.png",
  "SecurityBaselines": "Intune Service Color/SecurityBaselines.png",
  "SoftwareUpdate": "Intune Service Color/SoftwareUpdate.png",
  "Tools": "Intune Service Color/Tools.png",
  "ActivityLog": "Management and Governance Service Color/ActivityLog.png",
  "Advisor": "Management and Governance Service Color/Advisor.png",
  "Alerts": "Management and Governance Service Color/Alerts.png",
  "AutomationAccounts": "Management and Governance Service Color/AutomationAccounts.png",
  "Blueprints": "Management and Governance Service Color/Blueprints.png",
  "CostManagement+Billing": "Management and Governance Service Color/CostManagement+Billing.png",
  "DiagnosticSettings": "Management and Governance Service Color/DiagnosticSettings.png",
  "FreeServices": "Management and Governance Service Color/FreeServices.png",
  "GuestAssignments": "Management and Governance Service Color/GuestAssignments.png",
  "ManagedApplications": "Management and Governance Service Color/ManagedApplications.png",
  "Metrics": "Management and Governance Service Color/Metrics.png",
  "Monitor": "Management and Governance Service Color/Monitor.png",
  "NetworkWatcher": "Management and Governance Service Color/NetworkWatcher.png",
  "Policy": "Management and Governance Service Color/Policy.png",
  "RecoveryServicesVaults": "Management and Governance Service Color/RecoveryServicesVaults.png",
  "ResourceGraphExplorer": "Management and Governance Service Color/ResourceGraphExplorer.png",
  "SchedulerJobCollections": "Management and Governance Service Color/SchedulerJobCollections.png",
  "Solutions": "Management and Governance Service Color/Solutions.png",
  "AzureMediaPlayer": "Management and Governance Service Color/Media/AzureMediaPlayer.png",
  "ContentProtection": "Management and Governance Service Color/Media/ContentProtection.png",
  "MediaEncoding": "Management and Governance Service Color/Media/MediaEncoding.png",
  "MediaOn-Demand": "Management and Governance Service Color/Media/MediaOn-Demand.png",
  "AzureDatabaseMigrationServices": "Migrate Service Color/AzureDatabaseMigrationServices.png",
  "MigrationProjects": "Migrate Service Color/MigrationProjects.png",
  "SpatialAnchor": "Mixed Reality Service Icon/SpatialAnchor.png",
  "AzureAppService-Mobile": "Mobile Service Color/AzureAppService-Mobile.png",
  "AzureMobileEngagement": "Mobile Service Color/AzureMobileEngagement.png",
  "NotificationHubs": "Mobile Service Color/NotificationHubs.png",
  "ApplicationGateway": "Networking Service Color/ApplicationGateway.png",
  "ApplicationSecurityGroups": "Networking Service Color/ApplicationSecurityGroups.png",
  "AzureFirewall": "Networking Service Color/AzureFirewall.png",
  "CDNProfiles": "Networking Service Color/CDNProfiles.png",
  "Connections": "Networking Service Color/Connections.png",
  "DDOSProtectionPlans": "Networking Service Color/DDOSProtectionPlans.png",
  "DNSPrivateZones": "Networking Service Color/DNSPrivateZones.png",
  "DNSZones": "Networking Service Color/DNSZones.png",
  "ExpressRouteCircuits": "Networking Service Color/ExpressRouteCircuits.png",
  "FrontDoors": "Networking Service Color/FrontDoors.png",
  "LoadBalancers": "Networking Service Color/LoadBalancers.png",
  "LocalNetworkGateways": "Networking Service Color/LocalNetworkGateways.png",
  "NetworkInterfaces": "Networking Service Color/NetworkInterfaces.png",
  "networkSecurityGroups": "Networking Service Color/NetworkSecurityGroups.png",
  "On-premisesDataGateways": "Networking Service Color/On-premisesDataGateways.png",
  "PublicIPAddresses": "Networking Service Color/PublicIPAddresses.png",
  "ReservedIPAddresses": "Networking Service Color/ReservedIPAddresses.png",
  "RouteFilters": "Networking Service Color/RouteFilters.png",
  "RouteTables": "Networking Service Color/RouteTables.png",
  "ServiceEndpointPolicies": "Networking Service Color/ServiceEndpointPolicies.png",
  "TrafficManagerProfiles": "Networking Service Color/TrafficManagerProfiles.png",
  "VirtualNetwork": "Networking Service Color/VirtualNetwork.png",
  "VirtualNetworkGateways": "Networking Service Color/VirtualNetworkGateways.png",
  "VirtualNetworks": "Networking Service Color/VirtualNetworks.png",
  "VirtualWANs": "Networking Service Color/VirtualWANs.png",
  "CloudSimpleNodes": "Other Category Service Icon/CloudSimpleNodes.png",
  "CloudSimpleServices": "Other Category Service Icon/CloudSimpleServices.png",
  "Controllers": "Other Category Service Icon/Controllers.png",
  "CustomerLockbox": "Other Category Service Icon/CustomerLockbox.png",
  "Education": "Other Category Service Icon/Education.png",
  "ImageDefinitions": "Other Category Service Icon/ImageDefinitions.png",
  "ImageVersions": "Other Category Service Icon/ImageVersions.png",
  "ResourceExplorer": "Other Category Service Icon/ResourceExplorer.png",
  "SharedImageGalleries": "Other Category Service Icon/SharedImageGalleries.png",
  "TenantStatus": "Other Category Service Icon/TenantStatus.png",
  "WebAppFirewall": "Other Category Service Icon/WebAppFirewall.png",
  "AzureSentinel": "Security Service Color/AzureSentinel.png",
  "KeyVaults": "Security Service Color/KeyVaults.png",
  "SecurityCenter": "Security Service Color/SecurityCenter.png",
  "ArchiveStorage": "Storage Service Color/ArchiveStorage.png",
  "AzureFXTEdgeFiler": "Storage Service Color/AzureFXTEdgeFiler.png",
  "AzureNetAppfiles": "Storage Service Color/AzureNetAppfiles.png",
  "DataBox": "Storage Service Color/DataBox.png",
  "DataBoxEdge_DataBoxGateway": "Storage Service Color/DataBoxEdge_DataBoxGateway.png",
  "DataLakeStorage": "Storage Service Color/DataLakeStorage.png",
  "GeneralStorage": "Storage Service Color/GeneralStorage.png",
  "QueuesStorage": "Storage Service Color/QueuesStorage.png",
  "StorageAccounts": "Storage Service Color/StorageAccounts.png",
  "StorageExplorer": "Storage Service Color/StorageExplorer.png",
  "StorageSyncServices": "Storage Service Color/StorageSyncServices.png",
  "StorSimpleDataManagers": "Storage Service Color/StorSimpleDataManagers.png",
  "StorSimpleDeviceManagers": "Storage Service Color/StorSimpleDeviceManagers.png",
  "TableStorage": "Storage Service Color/TableStorage.png",
  "APIConnections": "Web Service Color/APIConnections.png",
  "AppServiceCertificates": "Web Service Color/AppServiceCertificates.png",
  "AppServiceDomains": "Web Service Color/AppServiceDomains.png",
  "AppServiceEnvironments": "Web Service Color/AppServiceEnvironments.png",
  "AppServicePlans": "Web Service Color/AppServicePlans.png",
  "AppServices": "Web Service Color/AppServices.png",
  "AzureMediaServices": "Web Service Color/AzureMediaServices.png",
  "AzureSearch": "Web Service Color/AzureSearch.png",
  "NotificationHubNamespaces": "Web Service Color/NotificationHubNamespaces.png",
  "SignalR": "Web Service Color/SignalR.png",
  "AzureCacheRedisProducticon": "Companies/AzureCacheRedisProducticon.png",
  "AzureHDInsight_COLOR": "Companies/AzureHDInsight_COLOR.png",
  "AzureHockeyApp_COLOR": "Companies/AzureHockeyApp_COLOR.png",
  "AzureOpenShift": "Companies/AzureOpenShift.png",
  "Cloud_Cycle": "Companies/Cloud_Cycle.png",
  "HD-Insight": "Companies/HD-Insight.png",
  "HockeyApp": "Companies/HockeyApp.png",
  "Kubernetes": "Companies/Kubernetes.png",
  "Logo-DC-OS": "Companies/Logo-DC-OS.png",
  "Logo-docker": "Companies/Logo-docker.png",
  "logo_pluralsight_mono": "Companies/logo_pluralsight_mono.png",
  "logo_pluralsight_twotone": "Companies/logo_pluralsight_twotone.png",
  "StackOverflow": "Companies/StackOverflow.png",
  "WebAppUmbraco": "Companies/WebAppUmbraco.png",
  "WebAppWordPress": "Companies/WebAppWordPress.png",
  "ActiveDirectoryFederationServicesProxy": "Flat Symbols/CnE_Enterprise/ActiveDirectoryFederationServicesProxy.png",
  "AD FS": "Flat Symbols/CnE_Enterprise/AD FS.png",
  "ADFS": "Flat Symbols/CnE_Enterprise/ADFS.png",
  "Android Phone": "Flat Symbols/CnE_Enterprise/Android Phone.png",
  "AndroidPhone": "Flat Symbols/CnE_Enterprise/AndroidPhone.png",
  "App generic": "Flat Symbols/CnE_Enterprise/App generic.png",
  "Application (blank)": "Flat Symbols/CnE_Enterprise/Application (blank).png",
  "Application server": "Flat Symbols/CnE_Enterprise/Application server.png",
  "Application(blankfortext)": "Flat Symbols/CnE_Enterprise/Application(blankfortext).png",
  "Application-Generic": "Flat Symbols/CnE_Enterprise/Application-Generic.png",
  "Applicationserver": "Flat Symbols/CnE_Enterprise/Applicationserver.png",
  "Azure pack": "Flat Symbols/CnE_Enterprise/Azure pack.png",
  "AzurePack": "Flat Symbols/CnE_Enterprise/AzurePack.png",
  "Backup, local": "Flat Symbols/CnE_Enterprise/Backup, local.png",
  "Backup, online": "Flat Symbols/CnE_Enterprise/Backup, online.png",
  "Backup,local": "Flat Symbols/CnE_Enterprise/Backup,local.png",
  "Backup,online": "Flat Symbols/CnE_Enterprise/Backup,online.png",
  "Calendar": "Flat Symbols/CnE_Enterprise/Calendar.png",
  "Certificate": "Flat Symbols/CnE_Enterprise/Certificate.png",
  "Client application": "Flat Symbols/CnE_Enterprise/Client application.png",
  "Clientapplication": "Flat Symbols/CnE_Enterprise/Clientapplication.png",
  "Cloud": "Flat Symbols/CnE_Enterprise/Cloud.png",
  "Cluster server": "Flat Symbols/CnE_Enterprise/Cluster server.png",
  "Clusterserver": "Flat Symbols/CnE_Enterprise/Clusterserver.png",
  "code file": "Flat Symbols/CnE_Enterprise/code file.png",
  "codefile": "Flat Symbols/CnE_Enterprise/codefile.png",
  "Connectors": "Flat Symbols/CnE_Enterprise/Connectors.png",
  "Database generic": "Flat Symbols/CnE_Enterprise/Database generic.png",
  "Database server": "Flat Symbols/CnE_Enterprise/Database server.png",
  "Database synchronization": "Flat Symbols/CnE_Enterprise/Database synchronization.png",
  "Databasegeneric": "Flat Symbols/CnE_Enterprise/Databasegeneric.png",
  "Databaseserver": "Flat Symbols/CnE_Enterprise/Databaseserver.png",
  "Databasesynchronization": "Flat Symbols/CnE_Enterprise/Databasesynchronization.png",
  "Device": "Flat Symbols/CnE_Enterprise/Device.png",
  "Direct Access (feature)": "Flat Symbols/CnE_Enterprise/Direct Access (feature).png",
  "Directaccess": "Flat Symbols/CnE_Enterprise/Directaccess.png",
  "Document": "Flat Symbols/CnE_Enterprise/Document.png",
  "DocumentDBfile": "Flat Symbols/CnE_Enterprise/DocumentDBfile.png",
  "Domain controller": "Flat Symbols/CnE_Enterprise/Domain controller.png",
  "Domaincontroller": "Flat Symbols/CnE_Enterprise/Domaincontroller.png",
  "Enterprise Building": "Flat Symbols/CnE_Enterprise/Enterprise Building.png",
  "Enterprise": "Flat Symbols/CnE_Enterprise/Enterprise.png",
  "EnterpriseBuilding": "Flat Symbols/CnE_Enterprise/EnterpriseBuilding.png",
  "File, general": "Flat Symbols/CnE_Enterprise/File, general.png",
  "File,general": "Flat Symbols/CnE_Enterprise/File,general.png",
  "Filter": "Flat Symbols/CnE_Enterprise/Filter.png",
  "Firewall": "Flat Symbols/CnE_Enterprise/Firewall.png",
  "Folder": "Flat Symbols/CnE_Enterprise/Folder.png",
  "Gateway": "Flat Symbols/CnE_Enterprise/Gateway.png",
  "Generic code": "Flat Symbols/CnE_Enterprise/Generic code.png",
  "Genericapp,namedtext": "Flat Symbols/CnE_Enterprise/Genericapp,namedtext.png",
  "Genericapp": "Flat Symbols/CnE_Enterprise/Genericapp.png",
  "Genericcode": "Flat Symbols/CnE_Enterprise/Genericcode.png",
  "Graph": "Flat Symbols/CnE_Enterprise/Graph.png",
  "Health monitoring": "Flat Symbols/CnE_Enterprise/Health monitoring.png",
  "Healthmonitoring": "Flat Symbols/CnE_Enterprise/Healthmonitoring.png",
  "Healthy": "Flat Symbols/CnE_Enterprise/Healthy.png",
  "Healthy_grey": "Flat Symbols/CnE_Enterprise/Healthy_grey.png",
  "Import generic": "Flat Symbols/CnE_Enterprise/Import generic.png",
  "Importgeneric": "Flat Symbols/CnE_Enterprise/Importgeneric.png",
  "Internet (hollow)": "Flat Symbols/CnE_Enterprise/Internet (hollow).png",
  "Internet(hollow)": "Flat Symbols/CnE_Enterprise/Internet(hollow).png",
  "Internet": "Flat Symbols/CnE_Enterprise/Internet.png",
  "iPhone": "Flat Symbols/CnE_Enterprise/iPhone.png",
  "Key, permissions": "Flat Symbols/CnE_Enterprise/Key, permissions.png",
  "Key,permissions": "Flat Symbols/CnE_Enterprise/Key,permissions.png",
  "Keyboard": "Flat Symbols/CnE_Enterprise/Keyboard.png",
  "Laptop computer": "Flat Symbols/CnE_Enterprise/Laptop computer.png",
  "Laptop": "Flat Symbols/CnE_Enterprise/Laptop.png",
  "Laptopcomputer": "Flat Symbols/CnE_Enterprise/Laptopcomputer.png",
  "Load balancer (Generic) white": "Flat Symbols/CnE_Enterprise/Load balancer (Generic) white.png",
  "Load balancer (Generic)": "Flat Symbols/CnE_Enterprise/Load balancer (Generic).png",
  "Load Testing": "Flat Symbols/CnE_Enterprise/Load Testing.png",
  "Loadbalancer(Generic)": "Flat Symbols/CnE_Enterprise/Loadbalancer(Generic).png",
  "LoadTesting": "Flat Symbols/CnE_Enterprise/LoadTesting.png",
  "lock unlocked, accessible": "Flat Symbols/CnE_Enterprise/lock unlocked, accessible.png",
  "Lock, protected": "Flat Symbols/CnE_Enterprise/Lock, protected.png",
  "Lock,protected": "Flat Symbols/CnE_Enterprise/Lock,protected.png",
  "Lock,unprotected": "Flat Symbols/CnE_Enterprise/Lock,unprotected.png",
  "Maintenance": "Flat Symbols/CnE_Enterprise/Maintenance.png",
  "Management console": "Flat Symbols/CnE_Enterprise/Management console.png",
  "Managementconsole": "Flat Symbols/CnE_Enterprise/Managementconsole.png",
  "Message": "Flat Symbols/CnE_Enterprise/Message.png",
  "Monitor running apps": "Flat Symbols/CnE_Enterprise/Monitor running apps.png",
  "Monitorrunningapps": "Flat Symbols/CnE_Enterprise/Monitorrunningapps.png",
  "Mouse": "Flat Symbols/CnE_Enterprise/Mouse.png",
  "Network card": "Flat Symbols/CnE_Enterprise/Network card.png",
  "Networkcard": "Flat Symbols/CnE_Enterprise/Networkcard.png",
  "Not allowed": "Flat Symbols/CnE_Enterprise/Not allowed.png",
  "Notallowed": "Flat Symbols/CnE_Enterprise/Notallowed.png",
  "Performance monitor": "Flat Symbols/CnE_Enterprise/Performance monitor.png",
  "Performance": "Flat Symbols/CnE_Enterprise/Performance.png",
  "Performancemonitor": "Flat Symbols/CnE_Enterprise/Performancemonitor.png",
  "Phone": "Flat Symbols/CnE_Enterprise/Phone.png",
  "Plug and play": "Flat Symbols/CnE_Enterprise/Plug and play.png",
  "Plugandplay": "Flat Symbols/CnE_Enterprise/Plugandplay.png",
  "PowerPoint": "Flat Symbols/CnE_Enterprise/PowerPoint.png",
  "Powershell script file": "Flat Symbols/CnE_Enterprise/Powershell script file.png",
  "Powershellscriptfile": "Flat Symbols/CnE_Enterprise/Powershellscriptfile.png",
  "Protocol stack": "Flat Symbols/CnE_Enterprise/Protocol stack.png",
  "Protocolstack": "Flat Symbols/CnE_Enterprise/Protocolstack.png",
  "Queue, general": "Flat Symbols/CnE_Enterprise/Queue, general.png",
  "Queue,general": "Flat Symbols/CnE_Enterprise/Queue,general.png",
  "RMS connector": "Flat Symbols/CnE_Enterprise/RMS connector.png",
  "RMSconnector": "Flat Symbols/CnE_Enterprise/RMSconnector.png",
  "Router": "Flat Symbols/CnE_Enterprise/Router.png",
  "rpd Remoting file": "Flat Symbols/CnE_Enterprise/rpd Remoting file.png",
  "rpdRemotingfile": "Flat Symbols/CnE_Enterprise/rpdRemotingfile.png",
  "Script file": "Flat Symbols/CnE_Enterprise/Script file.png",
  "Scriptfile": "Flat Symbols/CnE_Enterprise/Scriptfile.png",
  "Secure virtual machine": "Flat Symbols/CnE_Enterprise/Secure virtual machine.png",
  "Securevirtualmachine": "Flat Symbols/CnE_Enterprise/Securevirtualmachine.png",
  "Server (blade)": "Flat Symbols/CnE_Enterprise/Server (blade).png",
  "Server (generic)": "Flat Symbols/CnE_Enterprise/Server (generic).png",
  "Server directory": "Flat Symbols/CnE_Enterprise/Server directory.png",
  "Server farm": "Flat Symbols/CnE_Enterprise/Server farm.png",
  "Server rack": "Flat Symbols/CnE_Enterprise/Server rack.png",
  "Server(blade)": "Flat Symbols/CnE_Enterprise/Server(blade).png",
  "Server(generic)": "Flat Symbols/CnE_Enterprise/Server(generic).png",
  "Serverdirectory": "Flat Symbols/CnE_Enterprise/Serverdirectory.png",
  "Serverfarm": "Flat Symbols/CnE_Enterprise/Serverfarm.png",
  "Serverrack": "Flat Symbols/CnE_Enterprise/Serverrack.png",
  "Settings": "Flat Symbols/CnE_Enterprise/Settings.png",
  "Shared folder": "Flat Symbols/CnE_Enterprise/Shared folder.png",
  "Sharedfolder": "Flat Symbols/CnE_Enterprise/Sharedfolder.png",
  "Smartcard": "Flat Symbols/CnE_Enterprise/Smartcard.png",
  "Startup task": "Flat Symbols/CnE_Enterprise/Startup task.png",
  "Startuptask": "Flat Symbols/CnE_Enterprise/Startuptask.png",
  "Storage": "Flat Symbols/CnE_Enterprise/Storage.png",
  "stored procedures": "Flat Symbols/CnE_Enterprise/stored procedures.png",
  "storedprocedures": "Flat Symbols/CnE_Enterprise/storedprocedures.png",
  "Table": "Flat Symbols/CnE_Enterprise/Table.png",
  "Tablet": "Flat Symbols/CnE_Enterprise/Tablet.png",
  "Tool": "Flat Symbols/CnE_Enterprise/Tool.png",
  "triggers": "Flat Symbols/CnE_Enterprise/triggers.png",
  "Tunnel": "Flat Symbols/CnE_Enterprise/Tunnel.png",
  "UDF Function": "Flat Symbols/CnE_Enterprise/UDF Function.png",
  "UDFFunction": "Flat Symbols/CnE_Enterprise/UDFFunction.png",
  "Unhealthy": "Flat Symbols/CnE_Enterprise/Unhealthy.png",
  "USB": "Flat Symbols/CnE_Enterprise/USB.png",
  "User -Enterprise": "Flat Symbols/CnE_Enterprise/User -Enterprise.png",
  "User permissions": "Flat Symbols/CnE_Enterprise/User permissions.png",
  "User-Enterprise": "Flat Symbols/CnE_Enterprise/User-Enterprise.png",
  "Userpermissions": "Flat Symbols/CnE_Enterprise/Userpermissions.png",
  "Video": "Flat Symbols/CnE_Enterprise/Video.png",
  "Virtual Machine": "Flat Symbols/CnE_Enterprise/Virtual Machine.png",
  "Virtualmachine": "Flat Symbols/CnE_Enterprise/Virtualmachine.png",
  "Web server": "Flat Symbols/CnE_Enterprise/Web server.png",
  "Web": "Flat Symbols/CnE_Enterprise/Web.png",
  "Webserver": "Flat Symbols/CnE_Enterprise/Webserver.png",
  "WebSite (generic)": "Flat Symbols/CnE_Enterprise/WebSite (generic).png",
  "WebsiteGeneric": "Flat Symbols/CnE_Enterprise/WebsiteGeneric.png",
  "Windows Server": "Flat Symbols/CnE_Enterprise/Windows Server.png",
  "Windowsserver": "Flat Symbols/CnE_Enterprise/Windowsserver.png",
  "Wireless connection": "Flat Symbols/CnE_Enterprise/Wireless connection.png",
  "Wirelessconnection": "Flat Symbols/CnE_Enterprise/Wirelessconnection.png",
  "Workstation client": "Flat Symbols/CnE_Enterprise/Workstation client.png",
  "Workstationclient": "Flat Symbols/CnE_Enterprise/Workstationclient.png",
  "XML web service": "Flat Symbols/CnE_Enterprise/XML web service.png",
  "XMLwebservice": "Flat Symbols/CnE_Enterprise/XMLwebservice.png",
  "10green - Copy": "Flat Symbols/CnE_GeneralSymbols/10green - Copy.png",
  "10magenta": "Flat Symbols/CnE_GeneralSymbols/10magenta.png",
  "10orange": "Flat Symbols/CnE_GeneralSymbols/10orange.png",
  "10red": "Flat Symbols/CnE_GeneralSymbols/10red.png",
  "11green": "Flat Symbols/CnE_GeneralSymbols/11green.png",
  "11magenta": "Flat Symbols/CnE_GeneralSymbols/11magenta.png",
  "11orange": "Flat Symbols/CnE_GeneralSymbols/11orange.png",
  "11red": "Flat Symbols/CnE_GeneralSymbols/11red.png",
  "12green": "Flat Symbols/CnE_GeneralSymbols/12green.png",
  "12magenta": "Flat Symbols/CnE_GeneralSymbols/12magenta.png",
  "12orange": "Flat Symbols/CnE_GeneralSymbols/12orange.png",
  "12red": "Flat Symbols/CnE_GeneralSymbols/12red.png",
  "13green": "Flat Symbols/CnE_GeneralSymbols/13green.png",
  "13magenta": "Flat Symbols/CnE_GeneralSymbols/13magenta.png",
  "13orange": "Flat Symbols/CnE_GeneralSymbols/13orange.png",
  "13red": "Flat Symbols/CnE_GeneralSymbols/13red.png",
  "14green": "Flat Symbols/CnE_GeneralSymbols/14green.png",
  "14magenta": "Flat Symbols/CnE_GeneralSymbols/14magenta.png",
  "14orange": "Flat Symbols/CnE_GeneralSymbols/14orange.png",
  "14red": "Flat Symbols/CnE_GeneralSymbols/14red.png",
  "15green": "Flat Symbols/CnE_GeneralSymbols/15green.png",
  "15magenta": "Flat Symbols/CnE_GeneralSymbols/15magenta.png",
  "15orange": "Flat Symbols/CnE_GeneralSymbols/15orange.png",
  "15red": "Flat Symbols/CnE_GeneralSymbols/15red.png",
  "16green": "Flat Symbols/CnE_GeneralSymbols/16green.png",
  "16magenta": "Flat Symbols/CnE_GeneralSymbols/16magenta.png",
  "16orange": "Flat Symbols/CnE_GeneralSymbols/16orange.png",
  "16red": "Flat Symbols/CnE_GeneralSymbols/16red.png",
  "17green": "Flat Symbols/CnE_GeneralSymbols/17green.png",
  "17magenta": "Flat Symbols/CnE_GeneralSymbols/17magenta.png",
  "17orange": "Flat Symbols/CnE_GeneralSymbols/17orange.png",
  "17red": "Flat Symbols/CnE_GeneralSymbols/17red.png",
  "18green": "Flat Symbols/CnE_GeneralSymbols/18green.png",
  "18magenta": "Flat Symbols/CnE_GeneralSymbols/18magenta.png",
  "18orange": "Flat Symbols/CnE_GeneralSymbols/18orange.png",
  "18red": "Flat Symbols/CnE_GeneralSymbols/18red.png",
  "19green": "Flat Symbols/CnE_GeneralSymbols/19green.png",
  "19magenta": "Flat Symbols/CnE_GeneralSymbols/19magenta.png",
  "19orange": "Flat Symbols/CnE_GeneralSymbols/19orange.png",
  "19red": "Flat Symbols/CnE_GeneralSymbols/19red.png",
  "1green - Copy": "Flat Symbols/CnE_GeneralSymbols/1green - Copy.png",
  "1magenta": "Flat Symbols/CnE_GeneralSymbols/1magenta.png",
  "1orange": "Flat Symbols/CnE_GeneralSymbols/1orange.png",
  "1red": "Flat Symbols/CnE_GeneralSymbols/1red.png",
  "20green": "Flat Symbols/CnE_GeneralSymbols/20green.png",
  "20magenta": "Flat Symbols/CnE_GeneralSymbols/20magenta.png",
  "20orange": "Flat Symbols/CnE_GeneralSymbols/20orange.png",
  "20red": "Flat Symbols/CnE_GeneralSymbols/20red.png",
  "2green - Copy": "Flat Symbols/CnE_GeneralSymbols/2green - Copy.png",
  "2magenta": "Flat Symbols/CnE_GeneralSymbols/2magenta.png",
  "2orange": "Flat Symbols/CnE_GeneralSymbols/2orange.png",
  "2red": "Flat Symbols/CnE_GeneralSymbols/2red.png",
  "3green - Copy": "Flat Symbols/CnE_GeneralSymbols/3green - Copy.png",
  "3magenta": "Flat Symbols/CnE_GeneralSymbols/3magenta.png",
  "3orange": "Flat Symbols/CnE_GeneralSymbols/3orange.png",
  "3red": "Flat Symbols/CnE_GeneralSymbols/3red.png",
  "4green - Copy": "Flat Symbols/CnE_GeneralSymbols/4green - Copy.png",
  "4magenta": "Flat Symbols/CnE_GeneralSymbols/4magenta.png",
  "4orange": "Flat Symbols/CnE_GeneralSymbols/4orange.png",
  "4red": "Flat Symbols/CnE_GeneralSymbols/4red.png",
  "5green - Copy": "Flat Symbols/CnE_GeneralSymbols/5green - Copy.png",
  "5magenta": "Flat Symbols/CnE_GeneralSymbols/5magenta.png",
  "5orange": "Flat Symbols/CnE_GeneralSymbols/5orange.png",
  "5red": "Flat Symbols/CnE_GeneralSymbols/5red.png",
  "6green - Copy": "Flat Symbols/CnE_GeneralSymbols/6green - Copy.png",
  "6magenta": "Flat Symbols/CnE_GeneralSymbols/6magenta.png",
  "6orange": "Flat Symbols/CnE_GeneralSymbols/6orange.png",
  "6red": "Flat Symbols/CnE_GeneralSymbols/6red.png",
  "7green - Copy": "Flat Symbols/CnE_GeneralSymbols/7green - Copy.png",
  "7magenta": "Flat Symbols/CnE_GeneralSymbols/7magenta.png",
  "7orange": "Flat Symbols/CnE_GeneralSymbols/7orange.png",
  "7red": "Flat Symbols/CnE_GeneralSymbols/7red.png",
  "8green - Copy": "Flat Symbols/CnE_GeneralSymbols/8green - Copy.png",
  "8magenta": "Flat Symbols/CnE_GeneralSymbols/8magenta.png",
  "8orange": "Flat Symbols/CnE_GeneralSymbols/8orange.png",
  "8red": "Flat Symbols/CnE_GeneralSymbols/8red.png",
  "9green - Copy": "Flat Symbols/CnE_GeneralSymbols/9green - Copy.png",
  "9magenta": "Flat Symbols/CnE_GeneralSymbols/9magenta.png",
  "9orange": "Flat Symbols/CnE_GeneralSymbols/9orange.png",
  "9red": "Flat Symbols/CnE_GeneralSymbols/9red.png",
  "attachment": "Flat Symbols/CnE_GeneralSymbols/attachment.png",
  "attachments1": "Flat Symbols/CnE_GeneralSymbols/attachments1.png",
  "Audio": "Flat Symbols/CnE_GeneralSymbols/Audio.png",
  "Bug": "Flat Symbols/CnE_GeneralSymbols/Bug.png",
  "Building": "Flat Symbols/CnE_GeneralSymbols/Building.png",
  "Cable settop TV box": "Flat Symbols/CnE_GeneralSymbols/Cable settop TV box.png",
  "CablesettopTVbox": "Flat Symbols/CnE_GeneralSymbols/CablesettopTVbox.png",
  "Chart": "Flat Symbols/CnE_GeneralSymbols/Chart.png",
  "Checkmark success": "Flat Symbols/CnE_GeneralSymbols/Checkmark success.png",
  "Checkmark_Success": "Flat Symbols/CnE_GeneralSymbols/Checkmark_Success.png",
  "Continous Cycle Circle": "Flat Symbols/CnE_GeneralSymbols/Continous Cycle Circle.png",
  "ContinousCycleCircle": "Flat Symbols/CnE_GeneralSymbols/ContinousCycleCircle.png",
  "Crossout failure": "Flat Symbols/CnE_GeneralSymbols/Crossout failure.png",
