import { images } from '../../AzViz/src/nodejs/images';

describe('images', () => {
  it('should contain valid image paths for known Azure resources', () => {
    const knownResources = [
      'BatchAI',
      'BotServices',
      'CognitiveServices',
      'GenomicsAccounts',
      'MachineLearningServiceWorkspaces',
      'MachineLearningStudioWebServicePlans',
      'MachineLearningStudioWebServices',
      'MachineLearningStudioWorkspaces',
      'AnalysisServices',
      'AzureDatabricks',
      'AzureDataExplorerClusters',
      'DataFactories',
      'DataLakeAnalytics',
      'DataLakeStoreGen1',
      'EventHubClusters',
      'EventHubs',
      'HDInsightClusters',
      'Workspaces',
      'StreamAnalyticsJobs',
      'BatchAccounts',
      'CitrixVirtualDesktopsEssentials',
      'CloudServices',
      'CloudSimpleVirtualMachines',
      'Disks',
      'DiskSnapshots',
      'FunctionApps',
      'MeshApplications',
      'SAPHANAonAzure',
      'ServiceFabricClusters',
      'VMImages',
      'AvailabilitySets',
      'Non-azure-machine',
      'OSImages',
      'VM',
      'VM-Linux-non-azure',
      'VM-Linux',
      'VM-non-azure',
      'VM-windows-non-azure',
      'VM-windows',
      'virtualMachines',
      'VMScaleSets',
      'ContainerInstances',
      'ContainerRegistries',
      'KubernetesServices',
      'AzureCacheforRedis',
      'AzureCacheplusRedis',
      'AzureCosmosDB',
      'AzureDatabase(Generic)',
      'AzureDatabaseforMariaDBservers',
      'AzureDatabaseforMySQLservers',
      'AzureDatabaseforPostgreSQLservers',
      'AzureSQLDataWarehouse',
      'BlobStorage',
      'DataLake',
      'ElasticDatabasePools',
      'ElasticJobAgents',
      'ManagedDatabases',
      'SQLDatabases',
      'SQLManagedInstances',
      'SQLServers',
      'SQLServerstretchDatabases',
      'VirtualClusters',
      'VirtualDatacenter',
      'ApplicationInsights',
      'AzureArtifacts',
      'AzureBoards',
      'AzureDevOps',
      'AzureDevTestLabs',
      'AzurePipelines',
      'AzureRepos',
      'AzureTestPlans',
      'AllResources',
      'AzureHome',
      'DeveloperTools',
      'Help+Support',
      'Information',
      'ManagementGroups',
      'Marketplace',
      'QuickStartCenter',
      'Recent',
      'Reservations',
      'Resource',
      'ResourceGroups',
      'ServiceHealth',
      'SharedDashboard',
      'Subscriptions',
      'Support',
      'SupportRequests',
      'Tag',
      'Tags',
      'Templates',
      'TwoUserIcon',
      'UserHealthIcon',
      'UserIcon',
      'UserPrivacy',
      'UserResource',
      'What\'sNew',
      'AccessReview',
      'ActiveDirectory',
      'ActiveDirectoryConnectHealth',
      'AppRegistrations',
      'AzureADB2C',
      'AzureADDomainServices',
      'AzureADIdentityProtection',
      'AzureADPrivilegedIdentityManagement',
      'AzureInformationProtection',
      'ConditionalAccess',
      'EnterpriseApplications',
      'Identitygovernance',
      'ManagedIdentities',
      'APIManagementServices',
      'AppConfiguration',
      'AzureAPIforFHIR',
      'AzureDataCatalog',
      'AzureServiceBus',
      'AzureServiceBusRelays',
      'AzureStorSimpleDeviceManagers',
      'EventGridDomains',
      'EventGridSubscriptions',
      'EventGridTopics',
      'IntegrationAccounts',
      'IntegrationServiceEnvironments',
      'LogicApps',
      'LogicAppsCustomConnector',
      'SendGridAccounts',
      'ServiceCatalogManagedApplicationDefinitions',
      'SoftwareasaService(SaaS)',
      'AzureDigitalTwins',
      'AzureIoTHub',
      'AzureIoTHubSecurity',
      'AzureMaps',
      'AzureSphere',
      'DeviceProvisioningServices',
      'IoTCentralApplications',
      'TimeSeriesInsightsenvironments',
      'TimeSeriesInsightsEventsSources',
      'Windows10IoTCoreServices',
      'ClientApps',
      'DedicatedEventHub',
      'DeviceCompliance',
      'DeviceConfig',
      'DevicesGroups',
      'eBooks',
      'Enrollment',
      'ExchangeOn-PremisesAccess',
      'IntuneAppProtection',
      'ManagedDesktop',
      'SecurityBaselines',
      'SoftwareUpdate',
      'Tools',
      'ActivityLog',
      'Advisor',
      'Alerts',
      'AutomationAccounts',
      'Blueprints',
      'CostManagement+Billing',
      'DiagnosticSettings',
      'FreeServices',
      'GuestAssignments',
      'ManagedApplications',
      'Metrics',
      'Monitor',
      'NetworkWatcher',
      'Policy',
      'RecoveryServicesVaults',
      'ResourceGraphExplorer',
      'SchedulerJobCollections',
      'Solutions',
      'AzureMediaPlayer',
      'ContentProtection',
      'MediaEncoding',
      'MediaOn-Demand',
      'AzureDatabaseMigrationServices',
      'MigrationProjects',
      'SpatialAnchor',
      'AzureAppService-Mobile',
      'AzureMobileEngagement',
      'NotificationHubs',
      'ApplicationGateway',
      'ApplicationSecurityGroups',
      'AzureFirewall',
      'CDNProfiles',
      'Connections',
      'DDOSProtectionPlans',
      'DNSPrivateZones',
      'DNSZones',
      'ExpressRouteCircuits',
      'FrontDoors',
      'LoadBalancers',
      'LocalNetworkGateways',
      'NetworkInterfaces',
      'networkSecurityGroups',
      'On-premisesDataGateways',
      'PublicIPAddresses',
      'ReservedIPAddresses',
      'RouteFilters',
      'RouteTables',
      'ServiceEndpointPolicies',
      'TrafficManagerProfiles',
      'VirtualNetwork',
      'VirtualNetworkGateways',
      'VirtualNetworks',
      'VirtualWANs',
      'CloudSimpleNodes',
      'CloudSimpleServices',
      'Controllers',
      'CustomerLockbox',
      'Education',
      'ImageDefinitions',
      'ImageVersions',
      'ResourceExplorer',
      'SharedImageGalleries',
      'TenantStatus',
      'WebAppFirewall',
      'AzureSentinel',
      'KeyVaults',
      'SecurityCenter',
      'ArchiveStorage',
      'AzureFXTEdgeFiler',
      'AzureNetAppfiles',
      'DataBox',
      'DataBoxEdge_DataBoxGateway',
      'DataLakeStorage',
      'GeneralStorage',
      'QueuesStorage',
      'StorageAccounts',
      'StorageExplorer',
      'StorageSyncServices',
      'StorSimpleDataManagers',
      'StorSimpleDeviceManagers',
      'TableStorage',
      'APIConnections',
      'AppServiceCertificates',
      'AppServiceDomains',
      'AppServiceEnvironments',
      'AppServicePlans',
      'AppServices',
      'AzureMediaServices',
      'AzureSearch',
      'NotificationHubNamespaces',
      'SignalR',
      'AzureCacheRedisProducticon',
      'AzureHDInsight_COLOR',
      'AzureHockeyApp_COLOR',
      'AzureOpenShift',
      'Cloud_Cycle',
      'HD-Insight',
      'HockeyApp',
      'Kubernetes',
      'Logo-DC-OS',
      'Logo-docker',
      'logo_pluralsight_mono',
      'logo_pluralsight_twotone',
      'StackOverflow',
      'WebAppUmbraco',
      'WebAppWordPress',
      'ActiveDirectoryFederationServicesProxy',
      'AD FS',
      'ADFS',
      'Android Phone',
      'AndroidPhone',
      'App generic',
      'Application (blank)',
      'Application server',
      'Application(blankfortext)',
      'Application-Generic',
      'Applicationserver',
      'Azure pack',
      'AzurePack',
      'Backup, local',
      'Backup, online',
      'Backup,local',
      'Backup,online',
      'Calendar',
      'Certificate',
      'Client application',
      'Clientapplication',
      'Cloud',
      'Cluster server',
      'Clusterserver',
      'code file',
      'codefile',
      'Connectors',
      'Database generic',
      'Database server',
      'Database synchronization',
      'Databasegeneric',
      'Databaseserver',
      'Databasesynchronization',
      'Device',
      'Direct Access (feature)',
      'Directaccess',
      'Document',
      'DocumentDBfile',
      'Domain controller',
      'Domaincontroller',
      'Enterprise Building',
      'Enterprise',
      'EnterpriseBuilding',
      'File, general',
      'File,general',
      'Filter',
      'Firewall',
      'Folder',
      'Gateway',
      'Generic code',
      'Genericapp,namedtext',
      'Genericapp',
      'Genericcode',
      'Graph',
      'Health monitoring',
      'Healthmonitoring',
      'Healthy',
      'Healthy_grey',
      'Import generic',
      'Importgeneric',
      'Internet (hollow)',
      'Internet(hollow)',
      'Internet',
      'iPhone',
      'Key, permissions',
      'Key,permissions',
      'Keyboard',
      'Laptop computer',
      'Laptop',
      'Laptopcomputer',
      'Load balancer (Generic) white',
      'Load balancer (Generic)',
      'Load Testing',
      'Loadbalancer(Generic)',
      'LoadTesting',
      'lock unlocked, accessible',
      'Lock, protected',
      'Lock,protected',
      'Lock,unprotected',
      'Maintenance',
      'Management console',
      'Managementconsole',
      'Message',
      'Monitor running apps',
      'Monitorrunningapps',
      'Mouse',
      'Network card',
      'Networkcard',
      'Not allowed',
      'Notallowed',
      'Performance monitor',
      'Performance',
      'Performancemonitor',
      'Phone',
      'Plug and play',
      'Plugandplay',
      'PowerPoint',
      'Powershell script file',
      'Powershellscriptfile',
      'Protocol stack',
      'Protocolstack',
      'Queue, general',
      'Queue,general',
      'RMS connector',
      'RMSconnector',
      'Router',
      'rpd Remoting file',
      'rpdRemotingfile',
      'Script file',
      'Scriptfile',
      'Secure virtual machine',
      'Securevirtualmachine',
      'Server (blade)',
      'Server (generic)',
      'Server directory',
      'Server farm',
      'Server rack',
      'Server(blade)',
      'Server(generic)',
      'Serverdirectory',
      'Serverfarm',
      'Serverrack',
      'Settings',
      'Shared folder',
      'Sharedfolder',
      'Smartcard',
      'Startup task',
      'Startuptask',
      'Storage',
      'stored procedures',
      'storedprocedures',
      'Table',
      'Tablet',
      'Tool',
      'triggers',
      'Tunnel',
      'UDF Function',
      'UDFFunction',
      'Unhealthy',
      'USB',
      'User -Enterprise',
      'User permissions',
      'User-Enterprise',
      'Userpermissions',
      'Video',
      'Virtual Machine',
      'Virtualmachine',
      'Web server',
      'Web',
      'Webserver',
      'WebSite (generic)',
      'WebsiteGeneric',
      'Windows Server',
      'Windowsserver',
      'Wireless connection',
      'Wirelessconnection',
      'Workstation client',
      'Workstationclient',
      'XML web service',
      'XMLwebservice',
      '10green - Copy',
      '10magenta',
      '10orange',
      '10red',
      '11green',
      '11magenta',
      '11orange',
      '11red',
      '12green',
      '12magenta',
      '12orange',
      '12red',
      '13green',
      '13magenta',
      '13orange',
      '13red',
      '14green',
      '14magenta',
      '14orange',
      '14red',
      '15green',
      '15magenta',
      '15orange',
      '15red',
      '16green',
      '16magenta',
      '16orange',
      '16red',
      '17green',
      '17magenta',
      '17orange',
      '17red',
      '18green',
      '18magenta',
      '18orange',
      '18red',
      '19green',
      '19magenta',
      '19orange',
      '19red',
      '1green - Copy',
      '1magenta',
      '1orange',
      '1red',
      '20green',
      '20magenta',
      '20orange',
      '20red',
      '2green - Copy',
      '2magenta',
      '2orange',
      '2red',
      '3green - Copy',
      '3magenta',
      '3orange',
      '3red',
      '4green - Copy',
      '4magenta',
      '4orange',
      '4red',
      '5green - Copy',
      '5magenta',
      '5orange',
      '5red',
      '6green - Copy',
      '6magenta',
      '6orange',
      '6red',
      '7green - Copy',
      '7magenta',
      '7orange',
      '7red',
      '8green - Copy',
      '8magenta',
      '8orange',
      '8red',
      '9green - Copy',
      '9magenta',
      '9orange',
      '9red',
      'attachment',
      'attachments1',
      'Audio',
      'Bug',
      'Building',
      'Cable settop TV box',
      'CablesettopTVbox',
      'Chart',
      'Checkmark success',
      'Checkmark_Success',
      'Continous Cycle Circle',
      'ContinousCycleCircle',
      'Crossout failure',
    ];

    knownResources.forEach((resource) => {
      expect(images).toHaveProperty(resource);
      expect(images[resource]).toMatch(/\.(png|jpg|jpeg|svg)$/);
    });
  });

  it('should handle unknown resources gracefully', () => {
    const unknownResource = 'UnknownResource';
    expect(images).not.toHaveProperty(unknownResource);
  });
});
